pipeline{
    agent any

    tools {
         maven 'maven'
         jdk 'java'
    }

    stages{
       
         stage('Echo Stage') {
            steps {
                echo 'This is the end of the build!'
            }
        }
    }
}
